<?php

namespace BlogiridianBundle\Repository;

/**
 * CategoriaBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
