<?php
/**
 * Created by PhpStorm.
 * User: Iridian 4
 * Date: 19/07/2016
 * Time: 6:27 PM
 */

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

}