<?php

namespace AppBundle\Repository;

/**
 * NohabilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NohabilRepository extends \Doctrine\ORM\EntityRepository
{
}
