<?php

namespace AppBundle\Repository;

/**
 * RangoEdadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangoEdadRepository extends \Doctrine\ORM\EntityRepository
{
}
