<?php

namespace CarroiridianBundle\Repository;

/**
 * ConfiguracionPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
