<?php

namespace CarroiridianBundle\Repository;

/**
 * DedicatoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DedicatoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
