<?php

namespace CarroiridianBundle\Repository;

/**
 * FlorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlorRepository extends \Doctrine\ORM\EntityRepository
{
}
