<?php

namespace CarroiridianBundle\Repository;

/**
 * FloreroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloreroRepository extends \Doctrine\ORM\EntityRepository
{
}
