<?php

namespace CarroiridianBundle\Repository;

/**
 * InspiracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspiracionRepository extends \Doctrine\ORM\EntityRepository
{
}
