<?php

namespace CarroiridianBundle\Repository;

/**
 * InventarioAlmacenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioAlmacenRepository extends \Doctrine\ORM\EntityRepository
{
}
