<?php

namespace CarroiridianBundle\Repository;

/**
 * OcasionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OcasionRepository extends \Doctrine\ORM\EntityRepository
{
}
