<?php

namespace CarroiridianBundle\Repository;

/**
 * PrecioPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
