<?php

namespace CarroiridianBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
	public static function getTalleres(\Doctrine\ORM\EntityRepository $er){
		return $er->createQueryBuilder('p')
			->where('p.taller = 1');
	}
	public static function getAbasto(\Doctrine\ORM\EntityRepository $er){
		return $er->createQueryBuilder('p')
			->innerJoin('p.categoria','c',\Doctrine\ORM\Query\Expr\Join::WITH,'p.categoria = c.id AND c.abasto = 1');
	}
	public static function getFloreros(\Doctrine\ORM\EntityRepository $er){
		return $er->createQueryBuilder('p')
			->innerJoin('p.categoria','c',\Doctrine\ORM\Query\Expr\Join::WITH,'c.id = 4');
	}
}
