<?php

namespace CarroiridianBundle\Repository;

/**
 * RangoPrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangoPrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
