<?php

namespace CarroiridianBundle\Repository;

/**
 * TamanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TamanoRepository extends \Doctrine\ORM\EntityRepository
{
}
