<?php

namespace CarroiridianBundle\Repository;

/**
 * TipoInspiracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInspiracionRepository extends \Doctrine\ORM\EntityRepository
{
}
