<?php

namespace MercadoPagoBundle\Repository;

/**
 * DatosMercadoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosMercadoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
