<?php

namespace GeoBundle\Repository;

/**
 * CiudadSedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadSedeRepository extends \Doctrine\ORM\EntityRepository
{
}
