<?php

namespace GeoBundle\Repository;

/**
 * PaisFacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisFacturacionRepository extends \Doctrine\ORM\EntityRepository
{
}
